packaging_format = 2

id = "mattermost"
name = "Mattermost"
description.en = "Open source collaboration platform built for developers"
description.fr = "Plateforme de collaboration open source conçue pour les développeurs"

version = "7.9.1~ynh1"

maintainers = ["pmorinerie"]

[upstream]
license = "GPL-3.0-only"
website = "http://www.mattermost.org/"
admindoc = "https://docs.mattermost.com/guides/deployment.html"
userdoc = "https://docs.mattermost.com/guides/messaging.html"
code = "https://github.com/mattermost/mattermost-server"

[integration]
yunohost = ">= 11.1.15"
architectures = ["amd64", "armhf", "arm64"]
multi_instance = true
ldap = false
sso = false
disk = "50M"
ram.build = "350M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/mattermost"

    [install.init_main_permission]
    help.en = "If enabled, Mattermost will be accessible by users without a YunoHost account. This can be changed later via the webadmin."
    help.fr = "Si cette case est cochée, Mattermost sera accessible par l'utilisateur sans compte YunoHost. Vous pourrez changer ceci plus tard via l’interface d’administration."
    type = "group"
    default = "visitors"

    [install.admin]
    type = "user"

    [install.password]
    type = "password"

    [install.version]
    ask.en = "Choose the version you want to install"
    ask.fr = "Choisissez la version que vous souhaitez installer"
    help.en = "Use Team Edition for the open source version (ARM, ARM64 and x86-64 support) or Enterprise Edition if you want to use a license (x86-64 and ARM64 support)"
    help.fr = "Utilisez Team Edition pour la version open source (prise en charge ARM, ARM64 et x86-64) ou Édition Enterprise si vous souhaitez utiliser une licence (prise en charge x86-64 et ARM64)"
    type = "string"
    choices = ["Enterprise", "Team"]
    default = "Team"

    [install.language]
    ask.en = "Choose the language of the chat for the admin"
    ask.fr = "Choissisez la langue utilisée pour l'administrateur"
    type = "string"
    choices = ["de", "en", "es", "fr", "it", "pt"]
    default = "en"

    [install.team_display_name]
    ask.en = "Choose a Team name"
    ask.fr = "Choisissez le nom de l’équipe"
    type = "string"
    example = "Team"
    default = "Team"

[resources]
    [resources.sources]

        [resources.sources.main]
        amd64.url = "https://releases.mattermost.com/7.9.1/mattermost-team-7.9.1-linux-amd64.tar.gz"
        amd64.sha256 = "fbad64313f66e0ad66a0aea3772150b2360c1fddaa1ba83ad63a84ba65b4860f"
        arm64.url = "https://releases.mattermost.com/7.9.1/mattermost-team-7.9.1-linux-arm64.tar.gz"
        arm64.sha256 = "30a2e2cf5f79af70cd2a435d4e4487008579237461f6f2f533d7fc2d3f27bcc1"
        armhf.url = "https://github.com/SmartHoneybee/ubiquitous-memory/releases/download/v7.5.2/mattermost-v7.5.2-linux-arm.tar.gz"
        armhf.sha256 = "b26a4b676ee92ac848fa2993aa67559238ba7d8c1d0e6f7ffdd79ad8fb4942f3"

        [resources.sources.enterprise]
        amd64.url = "https://releases.mattermost.com/7.9.1/mattermost-enterprise-7.9.1-linux-amd64.tar.gz"
        amd64.sha256 = "c0014b6ac458d9b8d0a513e4574d4c9ced2b6029c45a1a79e10f201de7d707aa"
        arm64.url = "https://releases.mattermost.com/7.9.1/mattermost-enterprise-7.9.1-linux-arm64.tar.gz"
        arm64.sha256 = "c45a7e99705b96e73b1b5b9648a0dff54c89baf0a04ce6bac8ffd97ad25528c8"

    [resources.system_user]

    [resources.install_dir]

    [resources.data_dir]

    [resources.ports]

    [resources.permissions]
    main.url = "/"

    [resources.apt]
    packages = "postgresql pgloader"

    [resources.database]
    type = "postgresql"
