test_format = 1.0

[default]

    # -------------------------------
    # Default args to use for install
    # -------------------------------

    args.email = "john@gmail.com"
    args.admin_password = "admin!42"
    args.version = "Enterprise"
	args.team_display_name = "Mon équipe"

["Test with Team Edition"]

    only = ["install.subdir", "backup_restore", "upgrade" ]
    args.version = "Team"

